### ISSUE TITLE
values.yaml does not reflect the default installation

### ISSUE THREAD

**Issue by werebear73** [timescale/tobs#289] opened 2022-03-10 21:40 UTC
If I install tobs using the command line "tobs install", it deploys and all pods appears to launch and stay up and running on AWS EKS.  If I install using the values.yaml file ("tobs install -f values.yaml", grafana and promscale do not come up as ready.  I don't see anything in the documentation that states there are mandatory fields in the values.yaml  that need to be changed for proper launch.

**Comment by paulfantom** [comment] 2022-04-13 11:41
tobs CLI (`tobs install`) has some internal sauce that handles configuration options that are not exposed via helm chart. We are in the process of redesigning this, so expect changes in the future.

**Comment by paulfantom** [comment] 2022-05-04 10:38
I am closing this issue as tobs 0.11.0 (scheduled to be released on May 12) should deal with what is requested as we moved all the CLI logic into helm chart and there should be no "secret sauce". 

Feel free to reopen if you see that the issue is still present in tobs 0.11.0

**Closed by paulfantom** 2022-05-04 10:38 UTC
Labels: bug, helm, cli
