### ISSUE TITLE
TOBS 0.10.1 not working - AWS cluster versions 1.21 and 1.22

### ISSUE THREAD

**Issue by VictorMessina** [timescale/tobs#440] opened 2022-06-23 20:49 UTC
**What happened?**

I can't install tobs by CLI, i don't know why stop working.

**Did you expect to see something different?**

Yes.

**How to reproduce it (as minimally and precisely as possible)**:

Create a EKS version 1.21 or 1.22  with in AWS, before that connect into the cluster and follow the steps in tobs repo installing them by CLI.

I'm using kubectl and my version is 1.22.0

**Environment**

* tobs installation method:

- [x] cli
- [ ] helm chart

* tobs version: 0.10.1

  `0.10.1`

tobs install -n monitoring

cert-manager version v1.6.1 exists in the cluster, skipping the installation...

Installing The Observability Stack, this can take a few minutes

Error: could not install The Observability Stack: could not install The Observability Stack: chart requires kubeVersion: >= 1.23.0 which is incompatible with Kubernetes v1.22.9-eks-a64ea69

tobs version

Tobs CLI Version: 0.10.1, latest tobs helm chart version: 0.11.1

* Kubernetes version information:

  `1.22.0`

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

  AWS EKS

* tobs Logs:

```
Error: could not install The Observability Stack: could not install The Observability Stack: chart requires kubeVersion: >= 1.23.0 which is incompatible with Kubernetes v1.22.9-eks-a64ea69
```

**Anything else we need to know?**:

Before the release 0.11.1 everything works fine.

**Comment by paulfantom** [comment] 2022-06-24 06:41
This is not a bug. Your kubernetes cluster version is incompatible with tobs helm chart version as mentioned in logs:
```
chart requires kubeVersion: >= 1.23.0 which is incompatible with Kubernetes v1.22.9-eks-a64ea69
```

This is also noted in our compatibility matrix - https://github.com/timescale/tobs#tobs-vs-kubernetes and tobs 0.11.0 release notes - https://github.com/timescale/tobs/releases/tag/0.11.0

**Comment by paulfantom** [comment] 2022-06-27 09:08
0.11.2 is out. Bear in mind that using it on kubernetes version lower than 1.23 is still not supported and will most likely result in some alerts and grafana dashboards being broken.

I am closing this as 0.11.2 should resolve the issue. Please reopen if you feel the problem is not solved.

**Closed by paulfantom** 2022-06-27 09:08 UTC
Labels: bug
